{{- if .Values.buildPacks }}
{{- range $pkey, $pval := .Values.buildPacks }}
---
apiVersion: jenkins.io/v1
kind: BuildPack
metadata:
  name: {{ quote $pkey }}
spec:
  label: {{ quote $pval.label | default $pkey }}
  gitUrl: {{ quote $pval.gitUrl }}
  gitRef: {{ quote $pval.gitRef | default "master" }}
{{- end }}
{{- end }}
