owner: nxmatic
git-repo: jxlabs-nos-resources
package-path: .cr-release-packages
git-base-url: https://api.github.com/
git-upload-url: https://uploads.github.com/
charts-repo: https://nxmatic.github.io/jxlabs-nos-helmboot-resources/
index-path: .cr-index
