{{- if (eq "nexus" .Values.jxRequirements.repository) }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nexus
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
reclaimPolicy: Delete
mountOptions: 
  - uid=200
  - gid=200
{{- end }}
