{{- if and (or (eq "lighthouse" .Values.jxRequirements.webhook) (eq "prow" .Values.jxRequirements.webhook)) (eq "istio" .Values.jxRequirements.ingress.kind) }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: tide
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - tide{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
    port:
      name: http
      number: 80
      protocol: HTTP
---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tide
spec:
  gateways:
  - tide
  hosts:
    - tide{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
  http:
  - route:
    - destination:
        host: tide
      weight: 100
{{- end }}
