apiVersion: v1
data:
  password: {{ .Values.secrets.pipelineUser.token | b64enc | quote }}
  username: {{ .Values.secrets.pipelineUser.username | b64enc | quote }}
kind: Secret
metadata:
  name: jx-pipeline-git-{{ .Values.jxRequirements.cluster.gitKind | default "github" }}-{{ .Values.jxRequirements.cluster.gitName | default "github" }}
  annotations:
    build.knative.dev/git-0: {{ .Values.jxRequirements.cluster.gitServer | default "https://github.com" }}
    jenkins.io/credentials-description: API Token for acccessing {{ .Values.jxRequirements.cluster.gitServer | default "https://github.com" }}
      Git service inside pipelines
    jenkins.io/name: {{ .Values.jxRequirements.cluster.gitName | default "github" }}
    jenkins.io/url: {{ .Values.jxRequirements.cluster.gitServer | default "https://github.com" }}
  labels:
    jenkins.io/created-by: jx
    jenkins.io/credentials-type: usernamePassword
    jenkins.io/kind: git
    jenkins.io/service-kind: {{ .Values.jxRequirements.cluster.gitKind | default "github" }}
type: Opaque