apiVersion: v1
data:
{{- if .Values.secrets.gpg }}
  pubring.gpg: {{ .Values.secrets.gpg.pubring | b64enc | quote }}
  sec-jenkins.gpg: {{ .Values.secrets.gpg.secjenkins | b64enc | quote }}
  secring.gpg: {{ .Values.secrets.gpg.secring | b64enc | quote }}
  trustdb.gpg: {{ .Values.secrets.gpg.trustdb | b64enc | quote }}
{{- else }}
  pubring.gpg: ""
  sec-jenkins.gpg: ""
  secring.gpg: ""
  trustdb.gpg: ""
{{- end }}
kind: Secret
metadata:
  name: jenkins-release-gpg
type: Opaque