{{- $jx := .Values.jxRequirements -}}
{{- range $key, $env := .Values.jxRequirements.environments }}
{{- if $env.repository }}
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  name: "{{ $env.key }}"
  labels:
    jenkins.io/gitSync: "false"
spec:
  description: "the git repository for the {{ title $env.key }} environment"
  provider: {{ $jx.cluster.gitServer | default "https://github.com" | quote }}
  providerName: '{{ $jx.cluster.gitKind | default "github" }}'
  org: "{{ $env.owner | default $jx.cluster.environmentGitOwner }}"
  repo: "{{ $env.repository }}"
  httpCloneURL: "{{ $jx.cluster.gitServer | default "https://github.com" }}/{{ $env.owner | default $jx.cluster.environmentGitOwner }}/{{ $env.repository }}.git"
  url: "{{ $jx.cluster.gitServer | default "https://github.com" }}/{{ $env.owner | default $jx.cluster.environmentGitOwner }}/{{ $env.repository }}.git"
  scheduler:
    kind: Scheduler
{{- if $env.remoteCluster }}
  {{- if eq "dev" $env.key }}
    name: "release-only"
  {{- else }}
    name: "pr-only"
  {{- end -}}
{{- else }}
    name: "environment"
{{- end -}}
{{- end -}}
{{- end -}}
